apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-example-with-spring-boot
spec:
  replicas: 1
  selector:
    app: spring-boot-backend
  template:
    metadata:
      name: spring-boot-template
      labels:
        app: spring-boot-backend
    spec:
      containers:
        - name: spring-boot
          image: jongbeomlee/simple-spring-boot
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
